-- TABLAS PRINCIPALES
CREATE TABLE Roles (
  id_rol integer PRIMARY KEY,
  nombre_rol varchar
);

CREATE TABLE Usuario (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rol integer,
  nombre varchar NOT NULL,
  apellido_paterno varchar NOT NULL,
  apellido_materno varchar,
  correo varchar UNIQUE NOT NULL,
  contrasena varchar NOT NULL,
  telefono varchar(10),
  fecha_nacimiento date,
  curp varchar(18) UNIQUE,
  genero varchar(20),
  token_recuperacion varchar,
  token_expiracion timestamptz
);

-- HERENCIA DE USUARIOS
CREATE TABLE Dentista (
  id_dentista integer PRIMARY KEY,
  no_cedula varchar UNIQUE
);

CREATE TABLE Asistente (
  id_asistente integer PRIMARY KEY
);

CREATE TABLE Paciente (
  id_paciente integer PRIMARY KEY
);

-- DATOS EXCLUSIVOS DE PACIENTE
CREATE TABLE Direccion (
  id_direccion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_paciente integer, -- Se mantiene exclusivo para paciente
  calle varchar,
  num_ext varchar,
  num_int varchar,
  colonia varchar,
  alcaldia varchar,
  estado varchar,
  Codigo_postal varchar(5)
);

-- EXPEDIENTE CLÍNICO
CREATE TABLE Expediente (
  id_expediente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_paciente integer UNIQUE,
  id_dentista integer,
  fecha_creacion timestamptz DEFAULT NOW(),
  Observaciones_generales text
);

CREATE TABLE Odontograma (
  id_odontograma INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_expediente integer,
  datos_odontograma varchar,
  fecha_actualizacion timestamptz
);

CREATE TABLE Padecimientos (
  id_padecimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_padecimiento varchar,
  categoria_padecimiento varchar
);

CREATE TABLE Expediente_Padecimientos (
  id_exp_pad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_expediente integer,
  id_padecimiento integer,
  tipo_antecedente varchar NOT NULL,
  nota varchar,
  fecha_registro timestamptz DEFAULT NOW()
);

-- CITAS Y SEGUIMIENTO
CREATE TABLE Cita (
  id_cita INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_paciente integer,
  id_dentista integer,
  fecha_hora_inicio timestamptz,
  fecha_hora_fin timestamptz,
  tipo_cita varchar NOT NULL,
  estado varchar
);

CREATE TABLE Bitacora (
  id_bitacora INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_autor integer,
  id_cita integer,
  fecha_creacion timestamptz,
  descripcion text,
  accion_realizada varchar,
  estado_bitacora varchar
);

CREATE TABLE Consentimiento (
  id_consentimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cita integer,
  fecha_consentimiento timestamptz,
  archivo_url varchar NOT NULL
);

CREATE TABLE Catalogo_Procedimientos (
  id_procedimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar,
  descripcion varchar,
  dias_seguimiento integer,
  frecuencia_alertas integer
);

CREATE TABLE Seguimiento (
  id_seguimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cita integer UNIQUE,
  id_procedimiento integer,
  estado_seguimiento varchar,
  plan_cuidados text,
  indicaciones_medicas text,
  fecha_inicio date,
  fecha_fin date,
  enviado_24h boolean DEFAULT false,
  enviado_72h boolean DEFAULT false,
  fecha_envio_24h timestamptz,
  fecha_envio_72h timestamptz
);

-- CUESTIONARIOS
CREATE TABLE Cuestionario (
  id_cuestionario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nombre_cuestionario varchar,
  tipo_cuestionario varchar,
  descripcion varchar
);

CREATE TABLE Pregunta (
  id_pregunta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cuestionario integer,
  id_procedimiento_asociado integer,
  texto_pregunta varchar,
  tipo_control varchar
);

CREATE TABLE Respuesta_paciente (
  id_respuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pregunta integer,
  id_seguimiento integer,
  id_cuestionario integer,
  valor_respuesta text,
  fecha_respuesta timestamptz DEFAULT NOW()
);

COMMENT ON COLUMN Cita.estado IS 'Pendiente, Confirmada, Cancelada, Realizada';

-- RELACIONES (Foreign Keys)
ALTER TABLE Usuario ADD FOREIGN KEY (id_rol) REFERENCES Roles (id_rol);

-- Aquí respetamos tu decisión: Dirección ligada a Paciente
ALTER TABLE Direccion ADD FOREIGN KEY (id_paciente) REFERENCES Paciente (id_paciente);

ALTER TABLE Expediente ADD FOREIGN KEY (id_paciente) REFERENCES Paciente (id_paciente);
ALTER TABLE Expediente ADD FOREIGN KEY (id_dentista) REFERENCES Dentista (id_dentista);

ALTER TABLE Odontograma ADD FOREIGN KEY (id_expediente) REFERENCES Expediente (id_expediente);

ALTER TABLE Expediente_Padecimientos ADD FOREIGN KEY (id_expediente) REFERENCES Expediente (id_expediente);
ALTER TABLE Expediente_Padecimientos ADD FOREIGN KEY (id_padecimiento) REFERENCES Padecimientos (id_padecimiento);

ALTER TABLE Cita ADD FOREIGN KEY (id_paciente) REFERENCES Paciente (id_paciente);
ALTER TABLE Cita ADD FOREIGN KEY (id_dentista) REFERENCES Dentista (id_dentista);

ALTER TABLE Bitacora ADD FOREIGN KEY (id_autor) REFERENCES Usuario (id_usuario);
ALTER TABLE Bitacora ADD FOREIGN KEY (id_cita) REFERENCES Cita (id_cita);

ALTER TABLE Consentimiento ADD FOREIGN KEY (id_cita) REFERENCES Cita (id_cita);

ALTER TABLE Seguimiento ADD FOREIGN KEY (id_cita) REFERENCES Cita (id_cita);
ALTER TABLE Seguimiento ADD FOREIGN KEY (id_procedimiento) REFERENCES Catalogo_Procedimientos (id_procedimiento);

ALTER TABLE Pregunta ADD FOREIGN KEY (id_cuestionario) REFERENCES Cuestionario (id_cuestionario);
ALTER TABLE Pregunta ADD FOREIGN KEY (id_procedimiento_asociado) REFERENCES Catalogo_Procedimientos (id_procedimiento);

ALTER TABLE Respuesta_paciente ADD FOREIGN KEY (id_pregunta) REFERENCES Pregunta (id_pregunta);
ALTER TABLE Respuesta_paciente ADD FOREIGN KEY (id_seguimiento) REFERENCES Seguimiento (id_seguimiento);
ALTER TABLE Respuesta_paciente ADD FOREIGN KEY (id_cuestionario) REFERENCES Cuestionario (id_cuestionario);

ALTER TABLE Dentista ADD FOREIGN KEY (id_dentista) REFERENCES Usuario (id_usuario);
ALTER TABLE Asistente ADD FOREIGN KEY (id_asistente) REFERENCES Usuario (id_usuario);
ALTER TABLE Paciente ADD FOREIGN KEY (id_paciente) REFERENCES Usuario (id_usuario);